### ISSUE TITLE
How to test for NSE index (india)

### ISSUE THREAD

**Issue by RajeshDhalange** [robertmartin8/MachineLearningStocks#29]

**Comment by robertmartin8** [comment]
Hi Rajesh,

This will be quite difficult because it requires you to have the correct data. To be specific, you will need to acquire most of [these features](https://github.com/robertmartin8/MachineLearningStocks#features) for the companies you want the model to classify. If you manage to get this data, it's not too difficult, you just have to format it in the same shape as the testing dataframe and call `clf.predict`. 

Hope this helps!
Robert
